const Pool = require('../models/pool');
const { putobject } = require('../utils/s3'); 


// Create a new pool
exports.createPool = async (req, res) => {
  try {
    const { name, clientId, reelsUrl } = req.body;
    if (!name || !clientId) {
      return res.status(400).json({ error: 'Pool name and clientId are required' });
    }
    // poolId will be auto-generated by the model's default
    const pool = new Pool({ name, clientId, campaignId });
    await pool.save();
    res.status(201).json({ message: 'Pool created', pool });
  } catch (err) {
    res.status(500).json({ error: 'Failed to create pool', details: err.message });
  }
};

// Get all pools, optionally filter by clientId
exports.getPools = async (req, res) => {
  try {
    const { clientId } = req.query;
    const filter = clientId ? { clientId } : {};
    const pools = await Pool.find(filter).sort({ createdAt: -1 });
    res.json({ pools });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch pools', details: err.message });
  }
}; 

